"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def fiabonacci():
    f1, f2 = 0, 1
    sum_ = 0
    while f2 < 4e6:
        if f2 % 2 == 0:
            sum_ += f2
        f1, f2 = f2, f1 + f2
    return sum_


print(fiabonacci())
