"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def fiabonacci():
    a = 1
    b = 2
    d = 0
    for x in range(2, int(100)):
        if b % 2 == 0:
            d += b
        c = a
        a = b
        b += c
        if b >= 4e6:
            break
    return d


print(fiabonacci())
